title: matt's blog
description: >
    matt's blog
url: "https://mattsteadman.github.io"
github_username:  mattsteadman

markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge

navigation:
  - title: Home
    url: /index.html

theme: jekyll-theme-minimal
