title: matt's programming notes
description: >
    Notes on programming
url: "https://mattsteadman.co"
github_username:  mattsteadman

markdown: kramdown

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about/

theme: jekyll-theme-minimal
